import {
  DISPLAY_NAME,
  EMAIL,
  FIRST_NAME,
  LOGIN,
  MESSAGE,
  NEW_PASSWORD,
  NEW_PASSWORD_AGAIN,
  OLD_PASSWORD,
  PASSWORD,
  PASSWORD_AGAIN,
  PHONE,
  SEARCH,
  SECOND_NAME
} from './fieldNames'

const PASSWORD_REGULAR_EXPRESSION = /^(?=.*\d)(?=.*[A-Z])[a-zA-Z0-9]{8,40}$/
const NOT_EMPTY_REGULAR_EXPRESSION = /.+/
const NAME_REGULAR_EXPRESSION = /^[A-ZА-Я]+[a-zA-Zа-яА-Я-]*$/

export const REGULAR_EXPRESSIONS = {
  [LOGIN]: /(?!^\d+$)^[a-zA-Z0-9_-]{3,20}$/,
  [PASSWORD]: PASSWORD_REGULAR_EXPRESSION,
  [PASSWORD_AGAIN]: PASSWORD_REGULAR_EXPRESSION,
  [OLD_PASSWORD]: PASSWORD_REGULAR_EXPRESSION,
  [NEW_PASSWORD]: PASSWORD_REGULAR_EXPRESSION,
  [NEW_PASSWORD_AGAIN]: PASSWORD_REGULAR_EXPRESSION,
  [SEARCH]: NOT_EMPTY_REGULAR_EXPRESSION,
  [MESSAGE]: NOT_EMPTY_REGULAR_EXPRESSION,
  [PHONE]: /^(\+)?\d{10,15}$/,
  [EMAIL]:
    /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@(\.)[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/,
  [FIRST_NAME]: NAME_REGULAR_EXPRESSION,
  [SECOND_NAME]: NAME_REGULAR_EXPRESSION,
  [DISPLAY_NAME]: NAME_REGULAR_EXPRESSION
}
