export const SIGN_IN = '/'
export const SIGN_UP = '/sign-up'
export const PROFILE = '/settings'
export const EDIT_PROFILE = '/edit_profile'
export const EDIT_PASSWORD = '/edit_password'
export const MESSENGER = '/messenger'
export const NOT_FOUND = '/404'
export const SERVER_ERROR = '/500'
