export const SIGN_IN = '/'
export const SIGN_UP = '/sign_up'
export const PROFILE = '/profile'
export const EDIT_PROFILE = '/edit_profile'
export const EDIT_PASSWORD = '/edit_password'
export const CHATS = '/chats'
export const NOT_FOUND = '/404'
export const SERVER_ERROR = '/500'
